name: macos-beta-issues

on:
  issues:
    types: [opened, edited]

permissions:
  issues: write

jobs:
  label:
    runs-on: ubuntu-latest
    steps:
      - name: Check for macOS Beta checkbox
        id: check_checkbox
        uses: actions/github-script@v6
        with:
          script: |
            const issueBody = context.payload.issue.body;
            const macOSBetaChecked = issueBody.includes('- [x] Yes');
            return macOSBetaChecked;

      - name: Apply macos-beta label
        if: steps.check_checkbox.outputs.result == 'true'
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const issueNumber = context.issue.number;
            const label = 'macos-beta';
            await github.rest.issues.addLabels({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: issueNumber,
              labels: [label],
            });

      - name: Remove macos-beta label if unchecked
        if: steps.check_checkbox.outputs.result == 'false'
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const issueNumber = context.issue.number;
            const label = 'macos-beta';

            try {
              await github.rest.issues.removeLabel({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: issueNumber,
                name: label,
              });
            } catch (error) {
              if (error.status !== 404) {
                throw error;
              }
            };